### ISSUE TITLE
enums don't look good...

### ISSUE THREAD

**Issue by dakorpar** [contributte/qa#11]
after phpcbf it looks like this:
![image](https://user-images.githubusercontent.com/9303856/155187575-dc37a8b9-3f74-4980-a5b1-81eac1926dec.png)

and this is what's casing it:
![image](https://user-images.githubusercontent.com/9303856/155187631-9dce1836-02f9-4986-ab3e-2e6ac8cf6395.png)

IMHO this is how it SHOULD look like:
![image](https://user-images.githubusercontent.com/9303856/155187714-2c395ef5-f426-444a-894e-83e351e6a2dc.png)

**Comment by f3l1x** [comment]
You’re right. For now I suggest to exclude problematic sniffs. I believe it will be fixed in near future.

**Comment by f3l1x** [comment]
Enums seems fine by now.
