### ISSUE TITLE
Release stable version

### ISSUE THREAD

**Issue by martenb** [contributte/qa#6]
Any plan to release stable version?

https://github.com/ninjify/coding-standard/issues/26

**Comment by f3l1x** [comment]
I've made a little progress today. There are rulesets for PHP versions and also tests for these rulesets.

**Comment by martenb** [comment]
Can I help with something?

**Comment by f3l1x** [comment]
I wrote you on Slack, are you there? @martenb

**Comment by f3l1x** [comment]
There is first bumped version `v0.1.0`. You can play with it. :-)

Thank you for patience. Also thank you @martenb for help.
